version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 10

  fastapi:
    build: .
    env_file:
      - .env
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      sh -c "python scripts/bulk_index.py && uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  esdata: